env:
  global:
  - secure: |-
      eearIP/ytRNaNbdBly13B78aU73+Bb9cm+XseZyR3G8waU/BVFXlsoRSyRtcTcPOA6
      ve5PzxFmYND2dp5y2wuNMiF1pMaCdnNiW5sxPJ7DKaU+1eKWQ+hqv4Cl4mj+BsyG0/
      rxKLNeMlYVpToC4fXg/ebSHTrvGdLD1Hut80UEM=  # HEROKU_API_KEY for travis@niteoweb.com

install:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku keys:clear
  - yes | heroku keys:add
  - heroku plugins:install https://github.com/ddollar/heroku-anvil
  - heroku plugins:install https://github.com/glenngillen/heroku-exit-status.git

script:
  - heroku build -p -r heroku-buildpack-forego
  - heroku run "bin/_test" --app heroku-buildpack-forego
